baseurl: https://sislecv.github.io/
locale: zh-cn
theme: hugo-theme-stack
title: Rethinking
copyright: ""

# Theme i18n support. Configurations are per language.
languages:
    zh-cn:
        label: 中文
        title: Rethinking
        weight: 1
        params:
            sidebar:
                subtitle: Code, Create, Share

services:
    disqus:
        shortname: ""
    googleAnalytics:
        id: ""

pagination:
    pagerSize: 10

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: ""
    description: Code, Create, Share

    footer:
        since: 2026
        customText: ""

    dateFormat:
        published: "2006年01月02日"
        lastUpdated: "2006年01月02日 15:04"

    sidebar:
        emoji: "🚀"
        subtitle: Code, Create, Share
        avatar: "img/avatar.png"
        compact: false

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: "Licensed under CC BY-NC-SA 4.0"

    comments:
        enabled: false
        provider: disqus

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc
            - type: categories
            - type: tag-cloud

    opengraph:
        twitter:
            site: ""
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src: ""

    colorScheme:
        toggle: true
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: 首页
          url: /
          weight: -100
          params:
              icon: home
        - identifier: archives
          name: 归档
          url: /archives/
          weight: -90
          params:
              icon: archives
        - identifier: categories
          name: 分类
          url: /categories/
          weight: -80
          params:
              icon: categories
        - identifier: tags
          name: 标签
          url: /tags/
          weight: -70
          params:
              icon: hash
        - identifier: search
          name: 搜索
          url: /search/
          weight: -60
          params:
              icon: search
    social:
        - identifier: github
          name: GitHub
          url: https://github.com/Sislecv
          params:
              icon: brand-github
        - identifier: x
          name: X
          url: https://x.com/sislecv95122
          params:
              icon: brand-twitter
        - identifier: rss
          name: RSS
          url: /index.xml
          params:
              icon: rss
