baseurl: https://sislecv.github.io/
locale: zh-cn
theme: hugo-theme-stack
title: Rethinking
copyright: ""

# Theme i18n support. Configurations are per language.
languages:
    zh-cn:
        label: 中文
        title: Rethinking
        weight: 1
        params:
            sidebar:
                subtitle: Code, Create, Share

services:
    disqus:
        shortname: ""
    googleAnalytics:
        id: ""

pagination:
    pagerSize: 10

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: ""

    footer:
        since: 2026
        customText: ""

    dateFormat:
        published: ":date_full"
        lastUpdated: ":date_full"

    sidebar:
        emoji: "🚀"
        subtitle: Code, Create, Share
        avatar: "img/avatar.png"

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: false
            default: "Licensed under CC BY-NC-SA 4.0"

    comments:
        enabled: false
        provider: disqus

    widgets:
        homepage:
            - type: search
            - type: archives
              params:
                  limit: 5
            - type: categories
              params:
                  limit: 10
            - type: tag-cloud
              params:
                  limit: 10
        page:
            - type: toc

    opengraph:
        twitter:
            site: ""
            card: summary_large_image

    defaultImage:
        opengraph:
            enabled: false
            local: false
            src: ""

    colorScheme:
        toggle: true
        default: auto

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

menu:
    main:
        - identifier: home
          name: 首页
          url: /
          weight: 1
        - identifier: archives
          name: 归档
          url: /archives/
          weight: 2
        - identifier: search
          name: 搜索
          url: /search/
          weight: 3
